### ISSUE TITLE
Hearth/Hearthgold: Typo in Nerdbot's response when requesting a non-existent card.

### ISSUE THREAD

**Issue by pgoy-nerdery** [thenerdery/nerdbot#39]
##### Issue Description: #####
When performing `nerdbot hearth` or `nerdbot hearthgold` and providing a cardname that does not exist (such as "Ancient Silverback"), Nerdbot's response is "No card with this namo."

##### Expected Behavior: #####
"Name" is spelled correctly in Nerdbot's response.

##### Steps to Reproduce: #####
 1. Join a room with Nerdbot in it.
 2. Send the message "nerdbot hearthgold Giant Fuzzy Death Machine".
 3. Observe Nerdbot's response is "No card with this namo."

**Comment by JustinMullin** [comment]
Done got QA'd.  Fixed in https://github.com/thenerdery/nerdbot/pull/40.
