### ISSUE TITLE
There isn't any way to convey a (smug) emotion

### ISSUE THREAD

**Issue by natebrunette** [thenerdery/nerdbot#58]
Here's a good image:

![](http://www.moonbattery.com/ObamaSmug.jpg)

**Comment by douglaslinsmeyer** [comment]
:+1:

**Comment by kensykora** [comment]
I believe this is more of an hipchat server config request than a nerdbot request, given that emoticons in hipchat are a part of hipchat itself and not nerdbot. Please submit a request to SIS for this.

**Comment by kensykora** [comment]
also 

![texas-am-study-calls-obama-5th-best-president-in-america](https://cloud.githubusercontent.com/assets/64756/9183408/79fed38c-3f74-11e5-9287-c95261ba2292.jpg)
