### ISSUE TITLE
Animate command no longer grabs animated images

### ISSUE THREAD

**Issue by JustinMullin** [thenerdery/nerdbot#59]
Opening this ticket to track https://github.com/hubot-scripts/hubot-google-images/issues/10, which appears to be the root cause.  Looks like the legacy v1 Google images API suddenly stopped respecting the imgtype=animated flag.  If the hubot script we're using is updated at some point we can pull in the fix from there, until then 'nerdbot animate' will mostly return static images.

**Comment by JustinMullin** [comment]
@tvanfosson implemented a workaround in https://github.com/thenerdery/nerdbot/pull/60.

**Comment by jcarlso5** [comment]
#60 has been merged into master.
